const languages = [
   { label: "Afrikaans", code: "af" },
   { label: "Amharic", code: "am" },
   { label: "Arabic", code: "ar" },
   { label: "Asturian", code: "ast" },
   { label: "Azerbaijani", code: "az" },
   { label: "Bashkir", code: "ba" },
   { label: "Belarusian", code: "be" },
   { label: "Bulgarian", code: "bg" },
   { label: "Bengali", code: "bn" },
   { label: "Breton", code: "br" },
   { label: "Bosnian", code: "bs" },
   { label: "Catalan; Valencian", code: "ca" },
   { label: "Cebuano", code: "ceb" },
   { label: "Czech", code: "cs" },
   { label: "Welsh", code: "cy" },
   { label: "Danish", code: "da" },
   { label: "German", code: "de" },
   { label: "Greeek", code: "el" },
   { label: "English", code: "en" },
   { label: "Spanish", code: "es" },
   { label: "Estonian", code: "et" },
   { label: "Persian", code: "fa" },
   { label: "Fulah", code: "ff" },
   { label: "Finnish", code: "fi" },
   { label: "French", code: "fr" },
   { label: "Western Frisian", code: "fy" },
   { label: "Irish", code: "ga" },
   { label: "Gaelic; Scottish Gaelic", code: "gd" },
   { label: "Galician", code: "gl" },
   { label: "Gujarati", code: "gu" },
   { label: "Hausa", code: "ha" },
   { label: "Hebrew", code: "he" },
   { label: "Hindi", code: "hi" },
   { label: "Croatian", code: "hr" },
   { label: "Haitian; Haitian Creole", code: "ht" },
   { label: "Hungarian", code: "hu" },
   { label: "Armenian", code: "hy" },
   { label: "Indonesian", code: "id" },
   { label: "Igbo", code: "ig" },
   { label: "Iloko", code: "ilo" },
   { label: "Icelandic", code: "is" },
   { label: "Italian", code: "it" },
   { label: "Japanese", code: "ja" },
   { label: "Javanese", code: "jv" },
   { label: "Georgian", code: "ka" },
   { label: "Kazakh", code: "kk" },
   { label: "Central Khmer", code: "km" },
   { label: "Kannada", code: "kn" },
   { label: "Korean", code: "ko" },
   { label: "Luxembourgish; Letzeburgesch", code: "lb" },
   { label: "Ganda", code: "lg" },
   { label: "Lingala", code: "ln" },
   { label: "Lao", code: "lo" },
   { label: "Lithuanian", code: "lt" },
   { label: "Latvian", code: "lv" },
   { label: "Malagasy", code: "mg" },
   { label: "Macedonian", code: "mk" },
   { label: "Malayalam", code: "ml" },
   { label: "Mongolian", code: "mn" },
   { label: "Marathi", code: "mr" },
   { label: "Malay", code: "ms" },
   { label: "Burmese", code: "my" },
   { label: "Nepali", code: "ne" },
   { label: "Dutch; Flemish", code: "nl" },
   { label: "Norwegian", code: "no" },
   { label: "Northern Sotho", code: "ns" },
   { label: "Occitan (post 1500)", code: "oc" },
   { label: "Oriya", code: "or" },
   { label: "Panjabi; Punjabi", code: "pa" },
   { label: "Polish", code: "pl" },
   { label: "Pushto; Pashto", code: "ps" },
   { label: "Portuguese", code: "pt" },
   { label: "Romanian; Moldavian; Moldovan", code: "ro" },
   { label: "Russian", code: "ru" },
   { label: "Sindhi", code: "sd" },
   { label: "Sinhala; Sinhalese", code: "si" },
   { label: "Slovak", code: "sk" },
   { label: "Slovenian", code: "sl" },
   { label: "Somali", code: "so" },
   { label: "Albanian", code: "sq" },
   { label: "Serbian", code: "sr" },
   { label: "Swati", code: "ss" },
   { label: "Sundanese", code: "su" },
   { label: "Swedish", code: "sv" },
   { label: "Swahili", code: "sw" },
   { label: "Tamil", code: "ta" },
   { label: "Thai", code: "th" },
   { label: "Tagalog", code: "tl" },
   { label: "Tswana", code: "tn" },
   { label: "Turkish", code: "tr" },
   { label: "Ukrainian", code: "uk" },
   { label: "Urdu", code: "ur" },
   { label: "Uzbek", code: "uz" },
   { label: "Vietnamese", code: "vi" },
   { label: "Wolof", code: "wo" },
   { label: "Xhosa", code: "xh" },
   { label: "Yiddish", code: "yi" },
   { label: "Yoruba", code: "yo" },
   { label: "Chinese", code: "zh" },
   { label: "Zulu", code: "zu" },
];

module.exports = {
   languages,
};
